@echo off
setlocal EnableExtensions

rem Profile all JSON projection artifacts generated by generate_chunk27_projection_qa.bat.
rem Run from the repository root:
rem     scripts\profile_chunk27_projection_outputs.bat

cd /d "%~dp0\.."
set "OUT_DIR=scripts\outputs\chunk27_projection_qa"
set "REPORT=%OUT_DIR%\chunk27_artifact_profile.json"

if not exist "%OUT_DIR%" (
  echo ERROR: Projection QA directory not found: %OUT_DIR%
  exit /b 1
)

python scripts\profile_projection_artifacts.py "%OUT_DIR%" --recursive --out "%REPORT%"
if errorlevel 1 exit /b 1

echo Wrote %REPORT%
